### ISSUE TITLE
JALTOL Installation ERROR

### ISSUE THREAD

**Issue by PranutiChoppakatla** [atreebangalore/jaltol#5]
**Describe the bug**
There is an error that pops up everytime that QGIS is showing while installing JALTOL following all the instructions in JALTOL user manual.
**To Reproduce**
If using a custom shapefile please upload ZIP of the same to project google drive folder GISLayers and add link below.
1. 
2. 
3. 
4. 

**Expected behavior**
A clear and concise description of what you expected to happen instead.

**Screenshots**

**Desktop (please complete the following information):**
![unnamed](https://user-images.githubusercontent.com/99713334/165239464-9b5a8d0e-bcc6-426b-8da9-270c20203267.png)

 - OS Name and Version : Windows 10
 - QGIS Version: QGIS 3.16
![Installation_Error](https://user-images.githubusercontent.com/99713334/165240113-6300fcfd-ffb2-44d7-b918-3b6d57534f05.png)

**Additional context**
![Installation_Error](https://user-images.githubusercontent.com/99713334/165240213-17c8a33b-0876-4c69-96b6-383ea034c479.png)

**Comment by craigdsouza** [comment]
The issue was the 'qgis2web' plugin, it also has a resources.py file and it seems to be getting mixed up with the resources.py file for jaltol. 
The temporary solution for now was to uncheck the qgis2web plugin and that allows jaltol to work
p.s.: as we tried installing Jaltol 1.2 we noticed it is still the old version of the plugin.
